// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemMedyczny.Model;

#nullable disable

namespace SystemMedyczny.Model.Migrations
{
    [DbContext(typeof(BazaDanych))]
    [Migration("20240715154545_FiltrowanieUsunietych")]
    partial class FiltrowanieUsunietych
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("SystemMedyczny.Model.Encja", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Usunieta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uwagi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Encja");

                    b.HasDiscriminator().HasValue("Encja");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SystemMedyczny.Model.Apteka", b =>
                {
                    b.HasBaseType("SystemMedyczny.Model.Encja");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Apteka");
                });

            modelBuilder.Entity("SystemMedyczny.Model.FirmaFarmaceutyczna", b =>
                {
                    b.HasBaseType("SystemMedyczny.Model.Encja");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.ToTable("Encja", t =>
                        {
                            t.Property("Nazwa")
                                .HasColumnName("FirmaFarmaceutyczna_Nazwa");

                            t.Property("Telefon")
                                .HasColumnName("FirmaFarmaceutyczna_Telefon");
                        });

                    b.HasDiscriminator().HasValue("FirmaFarmaceutyczna");
                });

            modelBuilder.Entity("SystemMedyczny.Model.Lek", b =>
                {
                    b.HasBaseType("SystemMedyczny.Model.Encja");

                    b.Property<long?>("FirmaFarmaceutycznaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazwaHandlowa")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstancjaAktywna")
                        .HasColumnType("TEXT");

                    b.HasIndex("FirmaFarmaceutycznaId");

                    b.HasDiscriminator().HasValue("Lek");
                });

            modelBuilder.Entity("SystemMedyczny.Model.LekApteka", b =>
                {
                    b.HasBaseType("SystemMedyczny.Model.Encja");

                    b.Property<long?>("AptekaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LekId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("AptekaId");

                    b.HasIndex("LekId");

                    b.HasDiscriminator().HasValue("LekApteka");
                });

            modelBuilder.Entity("SystemMedyczny.Model.LekRecepta", b =>
                {
                    b.HasBaseType("SystemMedyczny.Model.Encja");

                    b.Property<int>("Ilosc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LekId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReceptaId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("LekId");

                    b.HasIndex("ReceptaId");

                    b.ToTable("Encja", t =>
                        {
                            t.Property("LekId")
                                .HasColumnName("LekRecepta_LekId");
                        });

                    b.HasDiscriminator().HasValue("LekRecepta");
                });

            modelBuilder.Entity("SystemMedyczny.Model.Lekarz", b =>
                {
                    b.HasBaseType("SystemMedyczny.Model.Encja");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRozpoczeciaPracy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataUrodzenia")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT");

                    b.Property<string>("NrUbezpieczenia")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specjalizacja")
                        .HasColumnType("TEXT");

                    b.ToTable("Encja", t =>
                        {
                            t.Property("Adres")
                                .HasColumnName("Lekarz_Adres");
                        });

                    b.HasDiscriminator().HasValue("Lekarz");
                });

            modelBuilder.Entity("SystemMedyczny.Model.Pacjent", b =>
                {
                    b.HasBaseType("SystemMedyczny.Model.Encja");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataUrodzenia")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LekarzId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwisko")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT");

                    b.Property<string>("NrUbezpieczenia")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT");

                    b.HasIndex("LekarzId");

                    b.ToTable("Encja", t =>
                        {
                            t.Property("Adres")
                                .HasColumnName("Pacjent_Adres");
                        });

                    b.HasDiscriminator().HasValue("Pacjent");
                });

            modelBuilder.Entity("SystemMedyczny.Model.Recepta", b =>
                {
                    b.HasBaseType("SystemMedyczny.Model.Encja");

                    b.Property<DateTime>("DataWystawienia")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LekarzId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PacjentId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("LekarzId");

                    b.HasIndex("PacjentId");

                    b.ToTable("Encja", t =>
                        {
                            t.Property("LekarzId")
                                .HasColumnName("Recepta_LekarzId");
                        });

                    b.HasDiscriminator().HasValue("Recepta");
                });

            modelBuilder.Entity("SystemMedyczny.Model.Lek", b =>
                {
                    b.HasOne("SystemMedyczny.Model.FirmaFarmaceutyczna", "FirmaFarmaceutyczna")
                        .WithMany()
                        .HasForeignKey("FirmaFarmaceutycznaId");

                    b.Navigation("FirmaFarmaceutyczna");
                });

            modelBuilder.Entity("SystemMedyczny.Model.LekApteka", b =>
                {
                    b.HasOne("SystemMedyczny.Model.Apteka", "Apteka")
                        .WithMany("Leki")
                        .HasForeignKey("AptekaId");

                    b.HasOne("SystemMedyczny.Model.Lek", "Lek")
                        .WithMany()
                        .HasForeignKey("LekId");

                    b.Navigation("Apteka");

                    b.Navigation("Lek");
                });

            modelBuilder.Entity("SystemMedyczny.Model.LekRecepta", b =>
                {
                    b.HasOne("SystemMedyczny.Model.Lek", "Lek")
                        .WithMany()
                        .HasForeignKey("LekId");

                    b.HasOne("SystemMedyczny.Model.Recepta", "Recepta")
                        .WithMany("Leki")
                        .HasForeignKey("ReceptaId");

                    b.Navigation("Lek");

                    b.Navigation("Recepta");
                });

            modelBuilder.Entity("SystemMedyczny.Model.Pacjent", b =>
                {
                    b.HasOne("SystemMedyczny.Model.Lekarz", "Lekarz")
                        .WithMany()
                        .HasForeignKey("LekarzId");

                    b.Navigation("Lekarz");
                });

            modelBuilder.Entity("SystemMedyczny.Model.Recepta", b =>
                {
                    b.HasOne("SystemMedyczny.Model.Lekarz", "Lekarz")
                        .WithMany()
                        .HasForeignKey("LekarzId");

                    b.HasOne("SystemMedyczny.Model.Pacjent", "Pacjent")
                        .WithMany()
                        .HasForeignKey("PacjentId");

                    b.Navigation("Lekarz");

                    b.Navigation("Pacjent");
                });

            modelBuilder.Entity("SystemMedyczny.Model.Apteka", b =>
                {
                    b.Navigation("Leki");
                });

            modelBuilder.Entity("SystemMedyczny.Model.Recepta", b =>
                {
                    b.Navigation("Leki");
                });
#pragma warning restore 612, 618
        }
    }
}
